### ISSUE TITLE
"Keyword 'MISSION' not found." for some fits files

### ISSUE THREAD

**Issue by keatonb** [KeplerGO/lightkurve#180] opened 2018-07-04 10:04 UTC
#### Problem description
Some Kepler light curve fits files downloaded with the wget scripts at https://archive.stsci.edu/kepler/publiclightcurves.html do not have the MISSION keyword in their headers (especially quarter 1 data for KIC 9821777 and above?). This missing keyword renders the data inaccessible to lightkurve.  I have not been able to set the mission attribute manually either. Can this attribute be None if the keyword is not in the header as is done for "Campaign" for Kepler data?

#### Example

```python
import lightkurve
klf = lightkurve.KeplerLightCurveFile(path='kplr009821777-2009166043257_llc.fits')  
print(klf.PDCSAP_FLUX)
```

#### Expected behavior
Should print the flux array, but instead returns KeyError: "Keyword 'MISSION' not found."

#### Environment:
- platform (e.g. Linux, OSX, Windows): Linux
- lightkurve version (e.g. 1.0b6): 1.0b8
- installation method (e.g. pip, conda, source): pip

**Comment by mirca** [comment] 2018-07-04 13:56
Hi @keatonb,

thanks a lot for investigating this!

However, I can't reproduce this error when I download the lightcurve file from the archive by doing:
```
>>> klf = KeplerLightCurveFile.from_archive(9821777, quarter=1)
>>> print(klf.PDCSAP_FLUX)
KeplerLightCurve(KIC: 9821777)
>>> klf.mission
'Kepler'
```

@barentsen what does this mean with respect to lightcurve files from [here](http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/)?

**Comment by texadactyl** [comment] 2018-07-04 14:01
If you find this ever to be true in the future, Astropy has proposed a header-edit process that worked for me (I was just monkeying around to see if it would work):
http://www.astropy.org/astropy-tutorials/FITS-header.html

Obviously, you need to know what goes in the element you are adding.

**Comment by keatonb** [comment] 2018-07-04 14:17
I also found that the individual files on the MAST archive do have this header, but the files in the tarballs (downloaded ~1 month ago) don't always.

**Comment by texadactyl** [comment] 2018-07-04 14:23
Okay, I found that particular FITS at 
http://archive.stsci.edu/pub/kepler/lightcurves/0098/009821777/kplr009821777-2009166043257_llc.fits
and it seems intact:
```
import lightkurve
PATH="http://archive.stsci.edu/pub/kepler/lightcurves/0098/009821777/kplr009821777-2009166043257_llc.fits"
klf = lightkurve.KeplerLightCurveFile(path=PATH)  
print(klf.PDCSAP_FLUX)
```

**Comment by keatonb** [comment] 2018-07-04 14:32
Here's the full header of the file I have:

> BITPIX  =                    8 / array data type                                
> NAXIS   =                    0 / number of array dimensions                     
> EXTEND  =                    T / file contains extensions                       
> NEXTEND =                    2 / number of standard extensions                  
> EXTNAME = 'PRIMARY '           / name of extension                              
> EXTVER  =                    1 / extension version number (not format version)  
> ORIGIN  = 'NASA/Ames'          / institution responsible for creating this file 
> DATE    = '2014-11-04'         / file creation date.                            
> CREATOR = '585725 FluxExporter2PipelineModule' / pipeline job and program used t
> PROCVER = 'svn+ssh://murzim/repo/soc/tags/release/9.2.22 r57227' / SW version   
> FILEVER = '5.0     '           / file format version                            
> TIMVERSN= 'OGIP/93-003'        / OGIP memo number for file format               
> TELESCOP= 'Kepler  '           / telescope                                      
> INSTRUME= 'Kepler Photometer'  / detector type                                  
> OBJECT  = 'KIC 9821777'        / string version of KEPLERID                     
> KEPLERID=              9821777 / unique Kepler target identifier                
> CHANNEL =                   39 / CCD channel                                    
> SKYGROUP=                   23 / roll-independent location of channel           
> MODULE  =                   12 / CCD module                                     
> OUTPUT  =                    3 / CCD output                                     
> QUARTER =                    1 / Observing quarter                              
> SEASON  =                    3 / mission season during which data was collected 
> DATA_REL=                   24 / version of data release notes for this file    
> OBSMODE = 'long cadence'       / observing mode                                 
> RADESYS = 'ICRS    '           / reference frame of celestial coordinates       
> RA_OBJ  =           287.236781 / [deg] right ascension                          
> DEC_OBJ =            46.614040 / [deg] declination                              
> EQUINOX =               2000.0 / equinox of celestial coordinate system         
> PMRA    =               0.0000 / [arcsec/yr] RA proper motion                   
> PMDEC   =               0.0000 / [arcsec/yr] Dec proper motion                  
> PMTOTAL =               0.0000 / [arcsec/yr] total proper motion                
> PARALLAX=                      / [arcsec] parallax                              
> GLON    =            77.331469 / [deg] galactic longitude                       
> GLAT    =            16.542294 / [deg] galactic latitude                        
> GMAG    =               14.833 / [mag] SDSS g band magnitude                    
> RMAG    =               14.317 / [mag] SDSS r band magnitude                    
> IMAG    =               14.151 / [mag] SDSS i band magnitude                    
> ZMAG    =               14.093 / [mag] SDSS z band magnitude                    
> D51MAG  =               14.622 / [mag] D51 magnitude,                           
> JMAG    =               13.103 / [mag] J band magnitude from 2MASS              
> HMAG    =               12.773 / [mag] H band magnitude from 2MASS              
> KMAG    =               12.736 / [mag] K band magnitude from 2MASS              
> KEPMAG  =               14.356 / [mag] Kepler magnitude (Kp)                    
> GRCOLOR =                0.516 / [mag] (g-r) color, SDSS bands                  
> JKCOLOR =                0.367 / [mag] (J-K) color, 2MASS bands                 
> GKCOLOR =                2.097 / [mag] (g-K) color, SDSS g - 2MASS K            
> TEFF    =                 5948 / [K] Effective temperature                      
> LOGG    =                4.329 / [cm/s2] log10 surface gravity                  
> FEH     =               -0.280 / [log10([Fe/H])]  metallicity                   
> EBMINUSV=                0.117 / [mag] E(B-V) redenning                         
> AV      =                0.361 / [mag] A_v extinction                           
> RADIUS  =                1.088 / [solar radii] stellar radius                   
> TMINDEX =            278003793 / unique 2MASS catalog ID                        
> SCPID   =                      / unique SCP processing ID                       
> CHECKSUM= '9A1KF61H9A1HC51H'   / HDU checksum updated 2014-11-04T22:03:44Z      
> END

**Comment by texadactyl** [comment] 2018-07-04 18:29
Thanks for the reference.  Downloading.

Is there any interest in having the FITS files repaired?
MISSION=?
Any other hdu[n] elements need to be added/updated/deleted?

**Comment by barentsen** [comment] 2018-07-04 22:20
It looks like the lightcurves in the tarballs under `lightcurves/tarfiles` at MAST are not the final versions.  For example, file `kplr100000926-2009166043257_llc.fits` obtained from `http://archive.stsci.edu/pub/kepler/lightcurves/tarfiles/Q1_public/public_Q1_long_6.tgz` shows the following version info in the header:

```
DATE    = '2014-11-04'         / file creation date.                            
CREATOR = '585867 FluxExporter2PipelineModule' / pipeline job and program used t
PROCVER = 'svn+ssh://murzim/repo/soc/tags/release/9.2.22 r57227' / SW version   
FILEVER = '5.0     '           / file format version                            
```

In contrast, the file obtained directly from `https://archive.stsci.edu/missions/kepler/lightcurves/1000/100000926/kplr100000926-2009166043257_llc.fits` shows the following version info:
```
DATE    = '2015-09-01'         / file creation date.                            
CREATOR = '796539 FluxExporter2PipelineModule' / pipeline job and program used t
PROCVER = 'svn+ssh://murzim/repo/soc/tags/release/9.3.22 r60269' / SW version   
FILEVER = '6.1     '           / file format version                            
```

It looks like the tarballs at MAST must be re-created i.e. updated to reflect the final Kepler data release.

I am going to close this issue because this is not a `lightkurve` problem, but I will be asking @JeffLCoughlin and @mustaric to work with MAST to resolve this problem.

**Comment by barentsen** [comment] 2018-07-04 22:21
(Many thanks @keatonb for bringing this issue to our attention :+1: :+1: :+1: )

**Closed by barentsen** 2018-07-04 22:20 UTC

**Comment by JeffLCoughlin** [comment] 2018-07-05 19:11
Yes many thanks @keatonb for finding this. I've notified our contact at MAST and will be sure to follow-up with them to fix it. Most of MAST is out today and tomorrow, so I expect a resolution sometime next week.

**Comment by texadactyl** [comment] 2018-07-05 19:17
Is that why their domain is down?
