### ISSUE TITLE
Discussions with Josh Schlieder for use-case driven tutorials for TESS applications 

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#593] opened 2019-09-12 22:25 UTC
From in person discussions with Josh Schlieder we came up with some ideas for common TESS use cases that could/should have a standalone lightkurve tutorial.  This Issue serves as live notes and summary of that discussion.

1. Making a custom lightcurve for FFI data

2. Custom local background subtraction

3. Make sure the tutorials are up-to-date or at least compatible with the master version of lightkurve.

**Comment by gully** [comment] 2019-10-01 21:48
A small update here, we've updated the "Cut out Target Pixel Files from TESS FFIs" tutorial:
https://docs.lightkurve.org/tutorials/03-cutting-out-tpfs-from-tess-ffis.html

I chose a demo with HAT-P-11b, which was observed in both Kepler prime and TESS Sector 14.

**Comment by barentsen** [comment] 2020-01-29 19:29
We recently added a tutorial focused on background removal in TESS:
https://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html

I'm tempted to close this issue because I believe we've addressed the most actionable needs, but of course many opportunities remain to further improve the tutorials!

**Closed by barentsen** 2020-01-29 19:29 UTC
Labels: discussion, tutorial
