### ISSUE TITLE
The search_tesscut() method appears broken

### ISSUE THREAD

**Issue by AngryKiwiNoises** [KeplerGO/lightkurve#595] opened 2019-09-17 23:40 UTC
#### Problem description
Search_tesscut() rarely works properly for me. It used to work with at least some regularity. As of a couple weeks ago, the only hitch was that it would not download a cutout if that same cutout had been downloaded immediately prior. Now I can't get it to work at all, and I've kind of hit a wall on my research project because of it. I honestly can't think of anything I've changed that would cause this to happen. Most of the targets I need to analyze don't turn up any results using search_targetpixelfile(), otherwise I'd just use that. 

#### Example

```python
import lightkurve
import numpy
import matplotlib as plt
from lightkurve import search_tesscut

#Search for and download target pixel file
TICarray = ['120896927', '178155732', '410214986', '441462736', '55652896', '290131778', '29857954', '394137592']

i = 0

searchparam = 'TIC ' + TICarray[i]
print('Searching...')
targetpixelfile = search_tesscut(searchparam).download(quality_bitmask='none')

#If the target pixel file was found and downloaded
#change it to a light curve file, plot it, and put it in a folder
if type(targetpixelfile) == lightkurve.targetpixelfile.TessTargetPixelFile:
    
    print('Found. Plotting...')
```

#### Expected behavior
It should download a cutout if there are search results for the TIC ID.

#### Actual behavior
```python
SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.
```
This happens even when I've been able to successfully download a cutout in the past.
#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows 10
-  lightkurve version (e.g. 1.0b6): v1.1
-  installation method (e.g. pip, conda, source): conda

**Comment by gully** [comment] 2019-09-18 20:53
I confirm that there are one or two bugs here.  First, the the MAST TESScut service appears to timeout due to high demand, and the default SearchError misleadingly states that the main interpretation could be a field too close to the edge.  A fix should be to parse the HTTP code to see if a timeout occurred.  Another, unrelated problem may be occurring if you are using the development version of astroquery, but this latter problem has not been confirmed.

**Comment by gully** [comment] 2019-09-18 20:57
A temporary workaround-- you can visually inspect the `urllib` HTTP codes:

```python
lightkurve.log.setLevel('INFO')
```

If you see `504 Gateway Timeout error` HTTP status code, you can surmise that the MAST servers were getting overwhelmed with traffic.

**Comment by gully** [comment] 2019-09-19 00:41
@mustaric points out a hiccup in TESScut from the developer version of astroquery:

>I talked to the astroquery.mast developer. Indeed in version 0.3.10dev MastClass has a function called resolve_object instead of _resolve_object. That is why [search_tesscut] is failing.

**Comment by gully** [comment] 2019-09-19 00:55
TODO:
- [ ] Catch the 504 HTTP Request Status and present an informative error message
- [ ] Future-proof against astroquery change to `_resolve_object()`

**Comment by gully** [comment] 2019-09-19 01:03
By the way-- @AngryKiwiNoises some other potential workarounds can be to check alternate TESScut venues to see if those are working. We have seen that some services continue to work while others do not (fickle behavior, not presently understood).

https://mast.stsci.edu/tesscut/
https://astroquery.readthedocs.io/en/latest/mast/mast.html

If you get the files locally you can still do:

```python
import lightkurve as lk
tpf = lk.TessTargetPixelFile('local_tesscut_file.fits')
```

**Comment by gully** [comment] 2019-09-24 18:20
@AngryKiwiNoises `search_tesscut()` should be working more reliably now.  Are you seeing improved performance?

**Comment by AngryKiwiNoises** [comment] 2019-09-26 21:24
@gully I actually ended up keeping all the files I needed locally, downloading them using astroquery, so I can't say, but thanks for looking into it!

**Comment by barentsen** [comment] 2019-10-02 19:28
I verified that the code snippet posted at the start of this issue works again, i.e. the `tesscut` service appears to be operating normally.  I think we can close this issue.  (Let's deal with improving the error message in case of `tesscut` outages as a separate issue!)

**Closed by barentsen** 2019-10-02 19:28 UTC

**Comment by rebekah9969** [comment] 2020-03-10 17:46
This command now appears to be broken again. With the same issues as before. Is there any solution?

**Comment by barentsen** [comment] 2020-03-10 17:55
@rebekah9969 It appears to work for me at this time.

There are a few ways in which `search_tesscut` might fail (server-side outages, name resolving issues, etc.)  Could you open an issue with the specific code tried and the error message that was produced? Thanks+++.

**Comment by rebekah9969** [comment] 2020-03-10 18:08
Hello Geert

I am actually going through the How to cut out Target Pixel Files from
Kepler Superstamps or TESS FFIs? tutorial.
tpf = search_result.download(cutout_size=20) gives...

---------------------------------------------------------------------------IndexError
                               Traceback (most recent call
last)~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_download_one(self, table, quality_bitmask, download_dir, cutout_size)
   150
download_dir,--> 151
cutout_size)    152             except Exception as exc:
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_fetch_tesscut_path(self, target, sector, download_dir, cutout_size)
 366         sec = TesscutClass().get_sectors(coords)--> 367
sector_name = sec[sec['sector'] == 1]['sectorName'][0]    368
if isinstance(cutout_size, int):
astropy/table/_column_mixins.pyx in
astropy.table._column_mixins._ColumnGetitemShim.__getitem__()
astropy/table/_column_mixins.pyx in astropy.table._column_mixins.base_getitem()
astropy/table/_column_mixins.pyx in
astropy.table._column_mixins.column_getitem()
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:
SearchError                               Traceback (most recent call
last)<ipython-input-9-b1057fb39ad8> in <module>      1 from lightkurve
import search_targetpixelfile----> 2 tpf =
search_result.download(cutout_size=20)
~/Desktop/TESS_LK/lightkurve/lightkurve/utils.py in wrapper(*args,
**kwargs)    471             sys.stdout = devnull    472
try:--> 473                 return f(*args, **kwargs)    474
  # restore to default    475             finally:
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in download(self,
quality_bitmask, download_dir, cutout_size)    236
              quality_bitmask=quality_bitmask,    237
                 download_dir=download_dir,--> 238
              cutout_size=cutout_size)    239     240
@suppress_stdout
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_download_one(self, table, quality_bitmask, download_dir, cutout_size)
   161                     raise SearchError('Unable to download FFI
cutout. Desired target '    162
'coordinates may be too near the edge of the FFI.'--> 163
                       'Error: {}'.format(exc))    164     165
    return _open_downloaded_file(path,
SearchError: Unable to download FFI cutout. Desired target coordinates
may be too near the edge of the FFI.Error: index 0 is out of bounds
for axis 0 with size 0

**Comment by barentsen** [comment] 2020-03-11 22:27
@rebekah9969 Weird.  The snippet below is working for me.  Does it still fail for you?  Please open a new issue if so!

```python
import lightkurve as lk
search_result = lk.search_tesscut('HAT-P-11', sector=14)
tpf = search_result.download(cutout_size=20)
```

**Comment by AJAX6255** [comment] 2020-08-26 23:05
Yes I was running the same tutorial today and it failed to run tesscut.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-70-ebef5de1d55a> in <module>
----> 1 lk.search_tesscut('026.0170142608, -15.9374795978')

AttributeError: module 'lightkurve' has no attribute 'search_tesscut'
Then I tried the following as suggested but got the error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-71-ac13b24bcfab> in <module>
----> 1 search_result = lk.search_tesscut('HAT-P-11', sector=14)
      2 tpf = search_result.download(cutout_size=20)

AttributeError: module 'lightkurve' has no attribute 'search_tesscut'
Finally I tried this and it didn't work either.
import lightkurve as lk
import numpy
import matplotlib as plt
from lightkurve import search_tesscut
ImportError: cannot import name 'search_tesscut'
I will try again in a few days.

**Comment by barentsen** [comment] 2020-08-26 23:15
@AJAX6255 The error message suggests that your installation of Lightkurve does not have the `search_tesscut` method, which is most likely because it is an older version. I recommend upgrading to Lightkurve v1.11 and trying again.

**Comment by AJAX6255** [comment] 2020-08-26 23:45
Just reinstalled Lightkurve and updated to 1.11.1 with same results.
No emergency - I will just skip this section of the tutorial and proceed.
Thanks for the incredibly fast reply.
I am a noob with a lot to learn with lightkurve.
Thanks again @barentsen!

**Comment by rebekah9969** [comment] 2020-08-26 23:48
I also had the same issue when i updated to the latest version.

**Comment by barentsen** [comment] 2020-08-27 00:41
I am unable to reproduce this problem using Lightkurve v1.11.1 installed via `pip`.

Please try the example below, which installs Lightkurve in a fresh environment.  If the example below fails, please open a new issue with diagnostic information (including platform and Python version used).  If the example below works, then it is likely a local path problem.

```bash
$ python -m venv tmpenv
$ tmpenv/bin/python -m pip install lightkurve
$ tmpenv/bin/python -c "import lightkurve; print(lightkurve.__version__)"
1.11.1
$ tmpenv/bin/python -c "import lightkurve as lk; print(lk.search_tesscut('HAT-P-11', sector=14))"
SearchResult containing 1 data products.

 #   observation   target_name productFilename distance
--- -------------- ----------- --------------- --------
  0 TESS Sector 14    HAT-P-11         TESSCut      0.0
```
