### ISSUE TITLE
from_archive() outputs a message that cannot be silenced.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#165] opened 2018-06-15 22:27 UTC
Since PR #150 the verbose keyword has been removed from from_archive. However it still prints an ugly message that cannot be silenced. We could capture this information and output it to the logger as debug information if we thought this was important? Or we could just always silence it.

![image](https://user-images.githubusercontent.com/14965634/41491883-912a2154-70b0-11e8-8130-7409c53c907d.png)

**Comment by barentsen** [comment] 2018-06-15 22:59
But you can silence this with `log.setLevel('WARNING')` right?  So the issue is that astroquery outputs it as `info` rather than `debug`?

I quite like that fact that, when a Python package downloads something, it is verbose about it by default (because downloads often hang your code on a plane etc...)  If setting `log.setLevel()` is too cumbersome, we could re-introduce a `verbose` argument that does it for the user.

**Comment by christinahedges** [comment] 2018-06-15 23:01
But there's no log level that will get rid of the message above.

**Comment by barentsen** [comment] 2018-06-15 23:14
You're right.  The issue is that astroquery's `_download_file` produces this message using a progressbar, not the logging module.  Hmmmmm.

**Comment by gully** [comment] 2018-06-26 19:51
Maybe make an issue / pull request in Astroquery to silence progressbar output upon request?

**Comment by barentsen** [comment] 2018-06-26 20:16
Right, I think a PR to astroquery would be a solution.  (Though it wouldn't be until the next astroquery release for the fix to become available.)

**Comment by texadactyl** [comment] 2018-07-03 15:14
When already in the cache ("Found cached file..."), I cannot see this behavior with WARN or ERROR but I can see the reported behavior with INFO or DEBUG.  So, Astroquery obeys its own log level.

If not yet cached locally ("Downloading ..."), then I see this behavior for any level.  The error seems to be that in {Astroquery treetop}/astroquery/query.py `_download_file`, the progress bar is being emitted without being conditioned on the log level.  See line 277 in https://github.com/astropy/astroquery/blob/master/astroquery/query.py.

I filed issue #1179 on the Astroquery github site.

**Comment by texadactyl** [comment] 2018-07-08 19:02
Astroquery issue #1179 was closed/rejected by Astroquery today saying it was a an Astropy issue.

After looking at the Astropy source code, it is apparent that the ProgressBarOrSpinner() API referenced at line 277 in query.py has no way of silencing it.  It would take a design & documentation change to get an enhancement (new quieter function that obeyed the log levels) through Astropy and then it would take an Astroquery change to use it in query.py, assuming either group had an interest.  I have no history/leverage with them.

@christinahedges - I am sympathetic if this is a lot of messages.

**Comment by barentsen** [comment] 2018-11-19 19:45
I believe this has successfully been resolved by #315.  Thank you @nksaunders!

**Closed by barentsen** 2018-11-19 19:45 UTC
