### ISSUE TITLE
ExoFOP sector list different from one retrieved from Lightkurve

### ISSUE THREAD

**Issue by martindevora** [KeplerGO/lightkurve#790] opened 2020-07-29 20:35 UTC
#### Problem description

When looking for sector information for [TIC 261136679 in ExoFOP](https://exofop.ipac.caltech.edu/tess/target.php?id=261136679) I'm finding only sectors 1 and 4 are listed. However, when retrieving the TIC from Lightkurve I find data for sectors 1, 4, 8, 11, 12, 13.

#### Example

```python
import lightkurve
lcf = lk.search_lightcurvefile("TIC 261136679", mission="TESS").download_all()
# Printing the result will show:   Sectors: [1, 4, 8, 11, 12, 13]
print("Sectors: " + [file.sector for file in lcf])

```

#### Expected behavior

I'm finding more sectors than expected for some TICs (not only the one used as example) when compared to ExoFOP information. It could also be ExoFOP portal missing sectors information somehow.

#### Environment
-  platform (e.g. Linux, OSX, Windows): LINUX
-  lightkurve version (e.g. 1.0b6): 1.11.1
-  installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment] 2020-07-29 23:29
Thank you for taking the time to open an issue @martindevora! :+1: 

I agree it looks like this target has been observed in at least 6 sectors:

![exofop](https://user-images.githubusercontent.com/817669/88863801-898b0b00-d1b8-11ea-9e5d-2ed4654712d4.png)

This looks like an ExoFOP rather than a Lightkurve issue to me.  I will pass this issue on to them. Thanks!

**Comment by martindevora** [comment] 2020-07-30 08:42
Thank you very much for your fast reply. Regards.

**Comment by barentsen** [comment] 2020-08-03 19:35
@martindevora ExoFOP confirmed to me it is an issue on their side.  I am going to close the issue here because it does not directly relate to Lightkurve. The ExoFOP Helpdesk will be the best place for follow-up questions.

Thanks again for reporting! :+1:

**Closed** 2020-08-03 19:35 UTC
