### ISSUE TITLE
lc.plot issue when running AstroPy version of LightCurve

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#751] opened 2020-06-12 20:42 UTC
Have been playing with the  AstroPy version of LightKurve and had an issue when running the following code...

!pip install --quiet --upgrade git+https://github.com/barentsen/lightkurve.git@timeseries-refactor
lcf = search_lightcurvefile('KIC 6922244', quarter=4).download()
lcf.plot() 

plot not created

When doing the above I also get the deprecated warning as expected but then if I switch to search_lightcurve I get the error "name 'search_lightcurve' is not defined".

**Comment by barentsen** [comment] 2020-06-12 21:21
@rebekah9969  Oops!  

There are two possible solutions:
* If using a notebook, can you try executing `%matplotlib inline`.
* If using a terminal, try `import matplotlib.pyplot as plt; plt.show()`.

Would you be willing to check if that resolves the issue?

**Comment by barentsen** [comment] 2020-06-13 02:06
@rebekah9969 Strange, I can't reproduce the `name 'search_lightcurve' is not defined` error.  Can you post a screenshot?

**Comment by barentsen** [comment] 2020-08-28 00:57
This was likely an installation or path issue.  I will close this issue for now, but please re-open if the problem re-appears! :+1:

**Closed by barentsen** 2020-08-28 00:57 UTC
