### ISSUE TITLE
Use intereact() to click on a data point and get corresponding image to display

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#214] opened 2018-08-03 22:24 UTC
#### Problem description
Interact (so awesome) nicely displays the pixel-level data and corresponding lightcurve data points when pressing the play button. However, I had a use case where I wanted to see the lightcurve and corresponding pixel-level image for about 20 cadences or so (a single transit event). When zoomed in on the transit event, pressing play has the points and images display way too fast. Using the slider bar is not precise enough and skips many cadences at a time --- it is difficult just to get it to rewind to before the transit event. As a result I can't see the pixel-level images corresponding to each cadence of this transit event (which would let me visually see if this target, or instead a nearby one, is dimming during transit.)

Ideally I'd want to either:

1) Click a data point, and have the corresponding image display.

2) A less-ideal alternative, be able to slow down the play speed so I could start it before the transit and have it slowly step through each cadence.

#### Environment:
- Linux
- 1.0b13
- pip

**Comment by barentsen** [comment] 2018-08-03 22:26
Note: I believe you can step through cadences, one at a time, using the keyboard arrows <- and ->.

**Comment by JeffLCoughlin** [comment] 2018-08-03 22:31
Ah yes that does work!  Solves what I needed to do.  Could add that as default message instead of my suggestions above.

**Comment by barentsen** [comment] 2018-08-03 22:32
Assigning to @gully to investigate whether making light curve data points clickable is a desired feature, and if so, implement it.

**Comment by gully** [comment] 2018-08-08 23:56
I see, so clicking the lightcurve point brings up the tpf image.  Yeah, that's a good and natural thing to do.

This custom behavior relates to the Cool Stars 20 Hack day--- the desire to have data in one figure respond to interactions in another figure.  Bokeh offers a "callback" strategy that we investigated at the hack day.  The problem is that it's pretty tricky to debug and requires javascript programming.  There are two python oriented work arounds--- pscript and running a Bokeh server.  I'm exploring both of these options.

**Comment by gully** [comment] 2018-09-17 23:19
Resolved in PR #216

**Closed by gully** 2018-09-17 23:19 UTC
