### ISSUE TITLE
Search fails and gives Empty or corrupt FITS file error

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#411] opened 2019-02-02 02:37 UTC
#### Problem description

I'm trying to download a known Kepler planet, when I put the ID into search I get a weird error message I've never seen before. This feels like a MAST problem? Can anyone reproduce?

#### Example

```python
import lightkurve as lk
tpf = lk.search_targetpixelfile('KIC 5868793', quarter=7).download()
```

![image](https://user-images.githubusercontent.com/14965634/52158751-519d1900-2650-11e9-9e35-f758a04f425b.png)

**Comment by barentsen** [comment] 2019-02-03 01:55
I am unable to reproduce this issue (see below).  My best guess is that something went wrong during the file transfer, causing a corrupt FITS file to live in your local `~/.lightkurve-cache`.  If that's the case, clearing out the cache should resolve this problem.  I will close this issue for now but please do re-open if clearing out the cache does not make the issue go away.

![screenshot from 2019-02-02 17-46-14](https://user-images.githubusercontent.com/817669/52171465-75289800-2712-11e9-9c92-1bfe98fe6f56.png)

**Closed** 2019-02-03 01:55 UTC
