### ISSUE TITLE
MAST name resolver returns incorrect coordinates for "EPIC 250105131"

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#764] opened 2020-06-23 19:01 UTC
#### Problem description

Previously acceptable target string values are now rejected.

#### Example

```import lightkurve as lk

mission = 'K2'
quality_bitmask=0
target = 'EPIC 250105131'
campaign = 15
cadence = 'long'
tpf = lk.search_targetpixelfile(target=target, mission=mission, campaign=campaign, 
  cadence=cadence).download(quality_bitmask=quality_bitmask)
'''

no longer works and produces this error:  No data found for target "EPIC 250105131".

This error will break many scripts/apps using lightkurve.  

Hack solution: Remove the space character: 'EPIC 250105131' --> 'EPIC250105131'  
Target values without a space character *do* work.

#### Expected behavior
<!-- Describe the behavior you expected and how it differs from the behavior observed in the example. -->

I expected the lk.search_targetpixelfile to work without any problems

#### Environment

-  platform: OSX
-  lightkurve version: v2.0.dev (with astropy>=4.0 changed in requirements.txt)
-  installation method: pip

**Comment by barentsen** [comment] 2020-06-23 21:07
Thanks for reporting this issue @KenMighell. :+1:

This appears to be an issue with the object name resolver on the MAST-side.  `EPIC250105131` resolves to the correct position of a K2 target, whereas `EPIC 250105131` resolves to a different part of the sky which was not observed by K2:

```python
>>> from astroquery.mast import MastClass
>>> MastClass().resolve_object(objectname="EPIC250105131")
<SkyCoord (ICRS): (ra, dec) in deg
    (233.971134, -14.220069)>
>>> MastClass().resolve_object(objectname="EPIC 250105131")
<SkyCoord (ICRS): (ra, dec) in deg
    (250.46875, 40.02472)>
```

@mustaric @scfleming Any idea why `EPIC 250105131` is resolved to a funny position?  Are there other catalogs with the EPIC prefix?

**Comment by scfleming** [comment] 2020-06-23 21:39
"EPIC 250105131" with a space must be getting caught by one of the other resolvers (normally I would have expected it to be Simbad or NED, but I don't think that resolves with either of those).  Note: instead of "EPIC xxxx" you can also use "K2 xxxx", and in that case using a space with this number works.  I'll file a ticket to understand at least what is being caught instead in the cae of using a space.  I've also had a ticket made for a while to change the order of things when something begins with a K2/Kepler/TESS special trigger, not sure when that work will get done though...for now, try using "K2 xxxx" and see if that helps in cases where there is a name conflict with something else.

**Comment by scfleming** [comment] 2020-06-24 16:21
It seems like this was a result of the MAST resolver caching old NED entries.  At one point it looks like NED might have had EPIC entries.  They currently do not, and we have since cleared the cache of any NED entries that begin with EPIC, so this should not happen again.

**Comment by barentsen** [comment] 2020-06-24 16:38
Thanks so much for the super fast answer @scfleming!! :pray: :+1:

I repeated the code example above and confirm the issue has been fixed. :tada: :partying_face: 

I could add a unit test for this case to the Lightkurve tests.  Does that make sense, or would I be adding useless load to the name resolver?

**Comment by scfleming** [comment] 2020-06-24 16:39
I don't think it would hurt, I doubt it would make a dent in normal name resolver loads.

**Comment by barentsen** [comment] 2020-06-25 20:25
Done!  I added a regression test for this issue here: https://github.com/KeplerGO/lightkurve/commit/960374c53a408594004bc572560eb237d1bc3aad

Thanks for reporting the issue @KenMighell! :+1:  

Closing in 3 ... 2 ... 1 ...

**Closed by barentsen** 2020-06-25 20:25 UTC
