### ISSUE TITLE
Lightkurve 2.0beta5 downloadall method throws exception

### ISSUE THREAD

**Issue by martindevora** [KeplerGO/lightkurve#938] opened 2021-01-29 08:14 UTC
Obtaining a lightcurvefile throws exception.

#### Example

```python
import lightkurve
lcf = lk.search_lightcurvefile("TIC 251848941", mission="TESS", cadence="short", sector=2).download_all()
```
The exception is like this:
```
Traceback (most recent call last):
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/sherlock.py", line 342, in __run_object
    time, flux, flux_err, star_info, transits_min_count, cadence, sectors = self.__prepare(object_info)
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/sherlock.py", line 530, in __prepare
    lc, star_info, transits_min_count, sectors, quarters = self.lightcurve_builders[type(object_info)].build(object_info, object_dir)
  File "/home/martin/git_repositories/sherlockpipe/sherlockpipe/objectinfo/preparer/MissionLightcurveBuilder.py", line 28, in build
    lcf = lk.search_lightcurvefile(str(mission_id), mission=mission, cadence="short", sector=object_info.sectors)\
  File "/home/martin/.local/lib/python3.8/site-packages/lightkurve/utils.py", line 499, in wrapper
    return f(*args, **kwargs)
  File "/home/martin/.local/lib/python3.8/site-packages/lightkurve/search.py", line 331, in download_all
    products.append(self._download_one(table=self.table[idx:idx+1],
  File "/home/martin/.local/lib/python3.8/site-packages/lightkurve/search.py", line 209, in _download_one
    return read(path, quality_bitmask=quality_bitmask, **kwargs)
  File "/home/martin/.local/lib/python3.8/site-packages/lightkurve/io/read.py", line 110, in read
    raise LightkurveError("Not recognized as a supported data product:\n"
lightkurve.utils.LightkurveError: Not recognized as a supported data product:
/home/martin/.lightkurve-cache/mastDownload/HLSP/hlsp_tasoc_tess_ffi_tic00251848941-s02-c0120_tess_v04_lc/hlsp_tasoc_tess_ffi_tic00251848941-s02-c0120_tess_v04_lc.fits
This file may be corrupt due to an interrupted download. Please remove it from your disk and try again.
Not recognized as a supported data product:
```

I think that the error happens in detect.py, when calling:
```
creator = header['creator'].lower()
```
because creator is not listed within the headers of the fits file of TASOC.

#### Expected behavior

A lightcurve should be downloaded for sector two.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Linux
-  lightkurve version (e.g. 1.0b6): 2.0beta5
-  installation method (e.g. pip, conda, source): pip

**Comment by martindevora** [comment] 2021-01-29 08:21
I tried re,oving the file and running again, but same result.

**Comment by barentsen** [comment] 2021-01-29 18:54
Oops!  The issue is that Lightkurve v2 now returns light curves from different pipelines.  In this case, a light curve from the `TASOC` pipeline is returned, in addition to the official light curve created by the `SPOC` pipeline (which would have been the only light curve returned previously):

<img width="833" alt="Screen Shot 2021-01-29 at 10 49 54 AM" src="https://user-images.githubusercontent.com/817669/106315237-cf846280-621f-11eb-81df-a57a1c65f680.png">

This fails because we still need to add a reader function for TASOC light curves. (Hence the error message: `"Not recognized as a supported data product:"` that's hidden in the exception trace.)

A quick workaround is to add `author="SPOC"` to the search operation, i.e.:
```python
lc = lk.search_lightcurve("TIC 251848941", mission="TESS", author="SPOC", cadence="short", sector=2).download()
```

In meanwhile, I'm going to make sure we add support for reading TASOC light curves.  Perhaps we also ought to make sure SPOC light curves appear at the top of the search results, to minimize the change in behavior compared to Lightkurve v1.

Thanks for reporting.  This is helpful!

**Comment by martindevora** [comment] 2021-01-29 20:20
II'll give a try to this `author="SPOC"` and come back with the results. Thanks for your amazing work!

**Comment by martindevora** [comment] 2021-01-29 20:24
However, I don't know how backwards compatible is to return two light curves where only one was expected. I don't think you need to keep the same behaviour from v1 to v2 if you are adding this better support for several pipelines.

**Comment by barentsen** [comment] 2021-01-30 00:05
v2 will definitely not be 100% backwards compatible with v1, but we try to minimize any changes as much as possible.  Over in 691f73ed8e78f19872f66566f83eeb00c0038969 I have now changed the behavior of search to show `author="SPOC"` products on top by default.

We still need to add support for reading TASOC files.  There is an issue open for that task already (#918), so I will go ahead and close this issue.  Feel free to re-open if you have any further questions! :+1:

**Closed by barentsen** 2021-01-30 00:05 UTC
