### ISSUE TITLE
`SFFCorrector.trend` does not provide the full trend when `windows` > 1

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#78] opened 2018-03-09 14:38 UTC
See title.

**Comment by christinahedges** [comment] 2018-06-04 23:44
@AndyTza, try this one on for size.

First you can watch this youtube video on how to use the SFF corrector in lightkurve
https://www.youtube.com/watch?v=gmVg7MIehd4

The written copy of the tutorial is here
http://lightkurve.keplerscience.org/tutorials/2.01-how-to-detrend.html

Follow these steps 
* Reproduce the issue
* Screenshot it breaking and add it here
* Find where in the code it is breaking, attempt a fix
* Push it to your fork (AndyTza/lightkurve)
* Open a Pull Request. We'll then go over your fix and work on it together to check it won't break lightkurve.

_I believe this tutorial from @gully explains how the SFF method works (?) but it isn't necessary for you to know that for this issue.
https://www.youtube.com/watch?v=3Vs9uWW-E84_

**Comment by AndyTza** [comment] 2018-06-06 00:05
<img width="1136" alt="screen shot 2018-06-05 at 5 04 13 pm" src="https://user-images.githubusercontent.com/22720676/41008903-9ac0a3d0-68e2-11e8-9918-cea9601c28cd.png">

Couldn't reproduce the same error.

**Comment by christinahedges** [comment] 2018-06-06 00:07
@barentsen I'm closing this since Andy can't reproduce it. If it's still a problem for you let's look at it together?

**Closed by christinahedges** 2018-06-06 00:07 UTC
Labels: bug
