### ISSUE TITLE
interact not working in jupyterlab

### ISSUE THREAD

**Issue by camelator** [KeplerGO/lightkurve#723] opened 2020-04-05 14:03 UTC
I am trying to use the lightkurve/interact function using this simple example:
from lightkurve import search_targetpixelfile
tpf = search_targetpixelfile("HL Tau", mission='K2', campaign=13).download()
tpf.interact()
as described here:
https://docs.lightkurve.org/tutorials/04-interact-with-lightcurves-and-tpf.html

Unfortunately there is no output.
I think my jupyterlab/interact  is working because the following example works perfectly:
%matplotlib widget
import matplotlib.pyplot as plt
plt.figure()
x = [1,2,3]
y = [4,5,6]
plt.plot(x,y)

I also tried to use the magic %matplotlib widget without results

I am using jupyterlab in a docker container at localhost:8888
lightkurve version is 1.9.1

Please, how to debug this issue ?

**Comment by dhomeier** [comment] 2020-04-08 04:04
@camelator have you tried explicitly providing the `output_notebook` URL as
`tpf.interact(notebook_url='127.0.0.1:8888')`
(or the respective URL your jupyterlab session appears in)?
I am using a standard Jupyter notebook, but under MacOS found that it apparently did not look up `localhost` correctly.

**Comment by camelator** [comment] 2020-04-08 09:08
@dhomeier many thanks for helping,
yes I already tried that, same result.
I am in a docker image based on Ubuntu 18.04

**Comment by dhomeier** [comment] 2020-04-08 14:10
This did not provide any diagnostics on my url lookup problems, so I don't know if it will give useful info for your case, but you could try
```
import logging
logging.basicConfig(filename='lightkurve.log', level=logging.INFO)
```
before the start of your lightkurve session.

**Comment by camelator** [comment] 2020-04-08 14:58
@dhomeier  thanks for that!
Here are the errors in the file:
INFO:astropy:Found cached file /home/jovyan/.lightkurve-cache/mastDownload/K2/ktwo210690913-c13_lc/ktwo210690913-c13_lpd-targ.fits.gz with expected size 8509290.
INFO:lightkurve.utils:8% (301/3944) of the cadences will be ignored due to the quality mask (quality_bitmask=1130799).
INFO:bokeh.server.server:Starting Bokeh server version 1.4.0 (running on Tornado 6.0.4)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)
INFO:astropy:Found cached file /home/jovyan/.lightkurve-cache/mastDownload/K2/ktwo210690913-c13_lc/ktwo210690913-c13_lpd-targ.fits.gz with expected size 8509290.
INFO:lightkurve.utils:8% (301/3944) of the cadences will be ignored due to the quality mask (quality_bitmask=1130799).
INFO:bokeh.server.server:Starting Bokeh server version 1.4.0 (running on Tornado 6.0.4)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)

and here the error displayed:

/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/opt/conda/lib/python3.7/site-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Mapping
8% (301/3944) of the cadences will be ignored due to the quality mask (quality_bitmask=1130799).

**Comment by dhomeier** [comment] 2020-04-08 16:34
Thanks; I don't see anything suspicious in the warnings, but the last part of the log

> INFO:lightkurve.utils:8% (301/3944) of the cadences will be ignored due to the quality mask (quality_bitmask=1130799).
> INFO:bokeh.server.server:Starting Bokeh server version 1.4.0 (running on Tornado 6.0.4)
> INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)

looks a but different for me:
```
INFO:lightkurve.utils:8% (301/3944) of the cadences will be ignored due to the quality mask (quality_bitmask=1130799).
INFO:bokeh.server.server:Starting Bokeh server version 2.0.1 (running on Tornado 6.0.3)
INFO:bokeh.server.tornado:User authentication hooks NOT provided (default user enabled)
INFO:tornado.access:200 GET /autoload.js?bokeh-autoload-element=1001&bokeh-absolute-url=http://127.0.0.1:56977&resources=none (127.0.0.1) 444.81ms
INFO:tornado.access:101 GET /ws?kernel_name=python3.8 (127.0.0.1) 1.01ms
INFO:bokeh.server.views.ws:WebSocket connection opened
INFO:bokeh.server.views.ws:ServerConnection created
```
where the `tornado.access` messages _only_ appear when the window is displayed by giving it the `127.0.0.1:8888` address. Unfortunately I don't have a lot of ideas how to proceed from here, other than checking your `tornado` installation.

**Comment by camelator** [comment] 2020-04-09 08:19
Looks like your tornado server received  a GET message and not on my side. I suspect no GET message was sent or my tornado server does not receive the GET message. Because I have simple examples working, I think I am in the first situation.
Anyway, I'll try to follow your recommendations.

many thanks.

**Comment by barentsen** [comment] 2020-05-18 18:56
Thanks++ for reporting this issue!  I'm sorry to hear `interact` isn't working!

Unfortunately I am not able to reproduce this issue either!

I am inclined to close this issue because it is likely to be a Bokeh or Jupyter issue. However please do re-open this issue if anyone is able to provide more details, or is able to reproduce the bug!

**Closed by barentsen** 2020-05-18 18:56 UTC
