### ISSUE TITLE
Error with LightCurve.flatten() after changing from 32bit to 64bit python

### ISSUE THREAD

**Issue by themrrigs** [KeplerGO/lightkurve#890] opened 2020-10-27 12:56 UTC
### Problem description
After changing from a 32bit to 64bit version of python the LightCurve.flatten() function now runs into an error. Installing a 32 bit version (3.7.9) again, the code now works.

#### Example
Code
```python
import lightkurve
def my_custom_corrector_func(lc):
    corrected_lc = lc.remove_nans().remove_outliers().flatten(window_length=401)
    return corrected_lc

TIC_no = "TIC 270577175"
search_result = lightkurve.search_lightcurvefile(TIC_no, mission='TESS', cadence='short')
search_result = verify_search_result(search_result, TIC)
print(search_result)
lcfs = search_result.download_all(download_dir=".")
stitched_lcfs = lcfs.PDCSAP_FLUX.stitch(corrector_func=my_custom_corrector_func)
```
Error:
```error
** On entry to DLASCLS parameter number  4 had an illegal value
** On entry to DLASCLS parameter number  4 had an illegal value
Traceback (most recent call last):
    File "c:/Users/Alex/Documents/TESS Project/TESS Python Scripts/2min_cadence_v2/main.py", line 153, in <module>
    main(270577175)
File "c:/Users/Alex/Documents/TESS Project/TESS Python Scripts/2min_cadence_v2/main.py", line 16, in main
    stitched_lcfs = lcfs.PDCSAP_FLUX.stitch(corrector_func=my_custom_corrector_func)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\lightkurve\collections.py", line 134, in stitch
    lcs = [corrector_func(lc) for lc in self]
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\lightkurve\collections.py", line 134, in <listcomp>
    lcs = [corrector_func(lc) for lc in self]
  File "c:/Users/Alex/Documents/TESS Project/TESS Python Scripts/2min_cadence_v2/main.py", line 38, in my_custom_corrector_func
    corrected_lc = lc.remove_nans().remove_outliers().remove_nans().flatten(window_length=401)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\lightkurve\lightcurve.py", line 513, in flatten
    trend_signal[l:h] = signal.savgol_filter(x=self.flux[mask][l:h],
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\signal\_savitzky_golay.py", line 335, in savgol_filter
    coeffs = savgol_coeffs(window_length, polyorder, deriv=deriv, delta=delta)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\signal\_savitzky_golay.py", line 137, in savgol_coeffs
    coeffs, _, _, _ = lstsq(A, y)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python38\lib\site-packages\scipy\linalg\basic.py", line 1221, in lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares
```
#### Expected behavior
It was working before changing to 64bit from 32bit

#### Environment

-  platform Windows:
-  lightkurve version (1.11.3):
-  installation method (pip):
-  python version (3.8.6 64 bit) and (3.7.9 64 bit):

**Comment by orionlee** [comment] 2020-11-03 00:31
That smells like some incompatibility problem on Windows between python, scipy (and might be numpy).
I could not reproduce it (Windows, python 3.7 64 bit)

See the following for a similar issue:
https://github.com/KeplerGO/lightkurve/issues/880#issuecomment-716038343

In short: 
- use Anaconda
- install all packages **and python itself** from `conda-forge` channel.

**Comment by barentsen** [comment] 2020-12-17 05:05
I am inclined to close this issue because it appears to be related to a specific Windows build of SciPy, rather than a bug or issue within Lightkurve itself.

I do encourage anyone to post additional information in this thread and/or re-open this issue if we think a change within Lightkurve can help remedy this problem!

Thanks++ for opening the issue @themrrigs!  I have no doubt it will help other users.

**Closed by barentsen** 2020-12-17 05:05 UTC
