### ISSUE TITLE
WARNING non stop errors in searching some stars (e.g: HR1996)

### ISSUE THREAD

**Issue by saeedm31** [KeplerGO/lightkurve#511] opened 2019-05-17 16:38 UTC
#### try:
pixels = lk.search_targetpixelfile('HR1996').download_all()
pixels = lk.search_targetpixelfile('HIP31592').download_all()

#### Problem:

WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
C
??s&?????_???$???m? [astropy.io.fits.card]????z???\I???
WARNING:astropy:The following header keyword is invalid or follows an unrecognized non-standard convention:
C
??s&?????_???$???m????C??g???;????????$???????z???\I???

#### Environment:
- platform (OSX - Python 3.6.4):
- lightkurve==1.0b29
- installation method (pip):

**Comment by barentsen** [comment] 2019-05-17 18:33
@saeedm31 Many thanks for reporting!  I'm sorry to hear you are encountering this problem.  We are going to try to look into this asap.

**Comment by barentsen** [comment] 2019-05-17 19:28
I seem unable to reproduce this issue (cf. screenshot below).  My best guess is that the error is caused by the presence of a corrupt file in the download cache.

@saeedm31 Would you be willing to try removing the contents of `~/.lightkurve-cache` and/or `~/.astropy/mastDownload` in your home directory, try again, and let us know if that resolves the issue?  Thanks+++!

Screenshot from my attempt:
![Screenshot from 2019-05-17 12-25-23](https://user-images.githubusercontent.com/817669/57951548-35d81e80-789f-11e9-82e8-faf66d154f98.png)

**Comment by saeedm31** [comment] 2019-05-17 20:13
@barentsen Thank you very much for your prompt reply and support. Your solution solved the issue.

**Comment by barentsen** [comment] 2019-05-17 20:29
@saeedm31 No problem!  We need to modify Lightkurve to produce a clear error message when this type of problem occurs!

**Comment by saeedm31** [comment] 2019-05-18 12:19
@barentsen Is there a way to call these files inside ~/.lightkurve-cache (*.fits files) and use lightkurve functions ? (and not download every time searching for a target) ? Thanks

**Comment by barentsen** [comment] 2019-05-20 14:50
@saeedm31 I would recommend downloading the files once and explicitly storing them in a directory of your choice.  Here is example code to do this for Kepler-10:
```python
import lightkurve as lk
tpfs = lk.search_targetpixelfile("Kepler-10").download_all()
for tpf in tpfs:
    filename = os.path.basename(tpf.path)
    tpf.to_fits("/your/custom/directory/" + filename)
```

In the future we will hopefully improve our caching mechanism so that `search_targetpixelfile` is much faster for previous queries, but that is not the case yet.

**Comment by barentsen** [comment] 2019-05-20 15:12
@saeedm31 Actually, perhaps an easier solution is to do this:

```python
import lightkurve as lk
MYDIR = "/your/favorite/directory"
lk.search_targetpixelfile('kepler-10').download_all(download_dir=MYDIR) 
for filename in glob.glob(MYDIR+"/**/*fits*", recursive=True): 
    tpf = lk.open(filename) 
```

**Comment by saeedm31** [comment] 2019-05-20 16:07
Thank you very much @barentsen . "tpf = lk.open(filename)" is exactly what I was looking for because then you can use the functions of light-curve analysis inside lk.

**Comment by barentsen** [comment] 2019-05-20 19:05
Over on #512 we have now merged an enhancement which ensures that a more-informative error message is shown when a corrupt file is present in the cache.

Thanks again for reporting this issue.  Feel free to open new issues if you have any questions or encounter new issues!  I think this one can be closed!

**Closed by barentsen** 2019-05-20 19:05 UTC
