### ISSUE TITLE
Do we need a lightcurve.from_csv() function?

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#144] opened 2018-06-07 20:58 UTC
I'm not certain this is definitely super useful, but some people might find it handy? It would essentially just wrap pandas.from_csv().

**Comment by barentsen** [comment] 2018-06-07 21:16
Yes!  In addition, we need a tutorial showing how to instantiate a `LightCurve` object from various non-Kepler file formats that astronomers are likely to use (ascii, csv, excel?)

**Comment by JeffLCoughlin** [comment] 2018-06-11 22:41
I imagine this might be part of the future ability to get some HLSPs that are in ascii/csv right now easily into FITS format?

**Comment by barentsen** [comment] 2019-11-20 18:48
Closing this issue because it is a duplicate of #289.

(We do not yet support reading in custom HLSPs or custom light curve file formats, but this will no doubt be a future feature, cf. #289.)

**Closed by barentsen** 2019-11-20 18:48 UTC
Labels: low priority, new-feature
